// TODO: Add some links to the documentation (for instance, link to the type a specific INamedAPIResource links to)

export { IAPIResourceList, INamedAPIResourceList } from './resource-lists';
export { IBerry, IBerryFirmness, IBerryFlavor, IBerryFlavorMap, IFlavorBerryMap } from './berries';
export { IContestEffect, IContestName, IContestType, ISuperContestEffect } from './contests';
export { IEncounterCondition, IEncounterConditionValue, IEncounterMethod } from './encounters';
export { IChainLink, IEvolutionChain, IEvolutionDetail, IEvolutionTrigger } from './evolution';
export { IGeneration, IPokedex, IPokemonEntry, IVersion, IVersionGroup } from './games';
export {
  IItem,
  IItemAttribute,
  IItemCategory,
  IItemFlingEffect,
  IItemHolderPokemon,
  IItemHolderPokemonVersionDetail,
  IItemPocket,
  IItemSprites,
} from './items';
export {
  IEncounterMethodRate,
  IEncounterVersionDetails,
  ILocation,
  ILocationArea,
  IPalParkArea,
  IPalParkEncounterSpecies,
  IPokemonEncounter,
  IRegion,
} from './locations';
export { IMachine } from './machines';
export {
  IContestComboDetail,
  IContestComboSets,
  IMove,
  IMoveAilment,
  IMoveBattleStyle,
  IMoveCategory,
  IMoveDamageClass,
  IMoveFlavorText,
  IMoveLearnMethod,
  IMoveMetaData,
  IMoveStatChange,
  IMoveTarget,
  IPastMoveStatValues,
} from './moves';
export {
  IAbility,
  IAbilityEffectChange,
  IAbilityFlavorText,
  IAbilityPokemon,
  IAwesomeName,
  ICharacteristic,
  IEggGroup,
  IGender,
  IGenus,
  IGrowthRate,
  IGrowthRateExperienceLevel,
  ILocationAreaEncounter,
  IMoveBattleStylePreference,
  IMoveStatAffect,
  IMoveStatAffectSets,
  INature,
  INaturePokeathlonStatAffect,
  INaturePokeathlonStatAffectSets,
  INatureStatAffectSets,
  INatureStatChange,
  IPalParkEncounterArea,
  IPokeathlonStat,
  IPokemon,
  IPokemonAbility,
  IPokemonColor,
  IPokemonForm,
  IPokemonFormSprites,
  IPokemonHabitat,
  IPokemonHeldItem,
  IPokemonHeldItemVersion,
  IPokemonMove,
  IPokemonMoveVersion,
  IPokemonShape,
  IPokemonSpecies,
  IPokemonSpeciesDexEntry,
  IPokemonSpeciesGender,
  IPokemonSpeciesVariety,
  IPokemonSprites,
  IPokemonStat,
  IPokemonType,
  IStat,
  IType,
  ITypePokemon,
  ITypeRelations,
} from './pokemon';
export {
  ILanguage,
  IAPIResource,
  IDescription,
  IEffect,
  IEncounter,
  IFlavorText,
  IGenerationGameIndex,
  IMachineVersionDetail,
  IName,
  INamedAPIResource,
  IVerboseEffect,
  IVersionEncounterDetail,
  IVersionGameIndex,
  IVersionGroupFlavorText,
} from './utility';
